### PR TITLE
Fix delete person tag bug

### LINKED ISSUE #219: [PE-D] Bug trying to add a new tag.
-------------
Labels: `severity.High` `type.FunctionalityBug`
original: CodingCookieRookie/ped#11

### LINKED ISSUE #241: Issue with contact commands creating but not removing non-existent tags.
In particular, the delete and edit tag commands have the capability of converting an existing tag to a non-existent tag. I.e. contact `person1` is the only contact under a specific `tag1` and this `tag1` does not have any sub-tag. `tag2` is a parent-tag of `tag1` with no other contacts attached. Deleting `person1` should remove `tag2` as well but does not.

### PR DESCRIPTION
**Pull request by chan-j-d**
Fixed indirect tag deletions to properly get rid of hanging tags (tags that should not exist but are still appear to be) involved in 
- editContactCommand (contact has tag removed, tag has goes from 1 contact to 0 contacts. With no child-tags, tag should be deleted too)
- deleteContactCommand (contact deleted might be the only contact in a tag with no child tags. Tag should therefore be deleted)
- editTagCommand (a parent-tag with no direct contacts and only one sub-tag has its only sub-tag removed. Tag should be deleted)
- any of the above causing a parent tag to have its only child tag deleted. If this parent tag has no direct contacts, it should be deleted too (same goes for any of its parent tags, etc.)

Update test cases for new methods implemented in `ContactTagIntegrationManager` that replaces the `AddressBook` methods in `ModelManager`.

Added a portion in UG to specify that tags can exist (and thus cannot be added) even if there are no contacts currently displayed that have them..

### CODE REVIEW

File: src/main/java/seedu/address/model/ContactTagIntegrationManager.java [hunk 1]
```diff
@@ -135,31 +132,61 @@ private void removeContactsUnderTagFromAddressBook(Tag tag) {
...
+        addressBook.removePerson(person);
+        for (Tag tag : personTags) {
+            if (!hasTag(tag)) {
+                deleteTag(tag);
+            }
+        }
+    }
+
+    /**
+     * Changes the {@code person} in the addressbook with {@code editedPerson}.
```
Comment (fyshhh) [inline src/main/java/seedu/address/model/ContactTagIntegrationManager.java]: should be "Changes... to..."

File: src/main/java/seedu/address/model/ContactTagIntegrationManager.java [hunk 2]
```diff
@@ -135,31 +132,61 @@ private void removeContactsUnderTagFromAddressBook(Tag tag) {
...
+     * If there {@code person} was the only contact in a tag and {@code editedPerson} has them removed,
```
Comment (fyshhh) [inline src/main/java/seedu/address/model/ContactTagIntegrationManager.java]: if the*? also should this be in present tense since the first sentence is also in present tense?

**Review by fyshhh — CHANGES_REQUESTED** [review]
some grammatical errors spotted

File: src/main/java/seedu/address/model/ModelManager.java [hunk 3]
```diff
@@ -218,7 +218,7 @@ public boolean hasReminder(Reminder reminder) {
 
     @Override
     public void deletePerson(Person target) {
-        addressBook.removePerson(target);
+        contactTagIntegrationManager.deletePerson(target);
```
Comment (bangyiwu) [inline src/main/java/seedu/address/model/ModelManager.java:221]: I don't really think contactTagIntegrationManager should handle the addressBook.removePerson aspect as well. It feels to me that you should separate it into two commands. Address book still handles removing of the person. But you can remove the tag first before address book removes the person. Correct me if I am wrong. The rest of this PR looks great though!

**Review by bangyiwu — CHANGES_REQUESTED** [review]

**Review by bangyiwu — COMMENTED** [review]
Just a comment regarding single responsibility principle

File: src/main/java/seedu/address/model/ModelManager.java (hunk 3 above)
Comment (chan-j-d) [reply src/main/java/seedu/address/model/ModelManager.java:221]: Well, I would argue that `ModelManager` is a Facade class. Having two methods implies that `ModelManager` is now handling logic that should be implemented elsewhere. 

Also, as mentioned in the PR, `deletePerson` does in fact affect `Tag`s as well. It could possibly remove a `Person`  that has `Tag1`. And `Tag1` might have only one contact which is this `Person`. This causes `Tag1` to be deleted. If `Tag2` is a parent-tag that only has `Tag1` as its only child tag and no direct contacts, then `Tag2` should also be deleted. Thus, I believe this, and the other edited methods should be implemented in `ContactTagIntegrationManager`. Given a choice, I would have refactored the entire `AddressBook` and `TagTree` into `ContactTagIntegrationManager` but it seems a little too late to do that. 

This was the cause of a bug that I found that I believe is the cause of the issue attached to this PR.

**Comment by chan-j-d** [comment]
> Just a comment regarding single responsibility principle

My understanding of this is that `ModelManager` class should definitely not handle the logic of both removing the `Person` and editing the `TagTree`.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 3 above)
Comment (bangyiwu) [reply src/main/java/seedu/address/model/ModelManager.java:221]: I get your point, we will just do this then, I will approve it as it is. Thanks for the clarification.

**Review by bangyiwu — APPROVED** [review]
lgtm

File: src/main/java/seedu/address/model/ModelManager.java (hunk 3 above)
Comment (chan-j-d) [reply src/main/java/seedu/address/model/ModelManager.java:221]: Thanks for pointing it out anyway. Appreciate the review!

**Review by fyshhh — APPROVED** [review]
lgtm! good job
