### PR TITLE
Implement multiple bug fixes

### LINKED ISSUE #193: [PE-D]  List All Contacts Feature: Incorrect response from cmd box
When listing all contacts, it says "Listed all persons" instead of "Listed all persons' contact".

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: augustinekau/ped#8

### LINKED ISSUE #194: [PE-D] Documentation Error for Listing all contacts in UG
In the example provided in UG for "Listing all contacts",

Using index 2 should sort by address in alphabetical order, not "by their names in alphabetical order."

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: augustinekau/ped#9

### LINKED ISSUE #195: [PE-D] Typing all command without any parameter shows Unknown command.
For add:

For clear:

For delete:

For edit:

For find:

For list:

For sort:

However, all these are not "Unknown command". 
Suggestion: For each command, if user typed with parameter, prompts and suggest them to type the parameter. Eg: User input: list. Should show: Use parameter "-c" to list all contacts, "-e" to ... "-r" to ...
instead of unknown command

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: augustinekau/ped#10

### LINKED ISSUE #196: [PE-D] Typing words after command "help" and "exit" still excecutes the command
Still pop up help:

However, it should be an invalid input. Should only match "help" or "exit". 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: augustinekau/ped#11

### LINKED ISSUE #199: [PE-D] [Athena] Compulsory fields are actually not compulsory
According to [UG](https://ay2021s1-cs2103t-w10-4.github.io/tp/UserGuide.html#adding-a-contact-add), `PHONE_NUMBER`, `EMAIL` and `ADDRESS` are compulsory, but in the app it is acceptable the omit them.

To replicate: type `add -c n/Alice Yeoh`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: StopTakingAllTheNames/ped#1

### LINKED ISSUE #204: [PE-D] [Athena] Saving section of UG is empty
Perhaps you could include a paragraph on whether the saving is automatic, or how to save if otherwise.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: StopTakingAllTheNames/ped#6

### LINKED ISSUE #208: [PE-D] Inconsistencies with Optional Fields in the UG
In the UG, it was stated that fields that are meant to be optional will be in [square brackets]. However some compulsory fields are indicated as optional in the UG.

Remember to change this in the UG to prevent any confusion! :)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: hyngkng/ped#4

### LINKED ISSUE #209: [PE-D] Embedded links for Introduction, Quick Start do not work.
No details provided.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: CodingCookieRookie/ped#1

### LINKED ISSUE #220: [PE-D] Table of contents links not working in UG
Table of contents links not working in UG

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: sun-yitao/ped#1

### PR DESCRIPTION
**Pull request by fyshhh**
this merge resolves #220 #209 #204 #199 #196 #195 #194 #193

this merge also closes #208 but it has been fixed by someone else (who did not link the issue)

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CommandWord.java [hunk 1]
```diff
@@ -1,29 +1,31 @@
...
+    ADD("add", List.of(CommandType.CONTACT, CommandType.EVENT, CommandType.TAG, CommandType.REMINDER)),
+    CLEAR("clear", List.of(CommandType.CONTACT, CommandType.EVENT)),
+    DELETE("delete", List.of(CommandType.CONTACT, CommandType.EVENT, CommandType.TAG, CommandType.REMINDER)),
+    EDIT("edit", List.of(CommandType.CONTACT, CommandType.EVENT, CommandType.TAG)),
+    EXIT("exit", new ArrayList<>()),
+    FIND("find", List.of(CommandType.CONTACT, CommandType.EVENT)),
+    HELP("help", new ArrayList<>()),
+    INTRO("intro", new ArrayList<>()),
+    LIST("list", List.of(CommandType.CONTACT, CommandType.EVENT, CommandType.TAG, CommandType.REMINDER)),
+    VIEW("view", List.of(CommandType.CONTACT, CommandType.EVENT, CommandType.TAG)),
```
Comment (chan-j-d) [inline src/main/java/seedu/address/logic/commands/CommandWord.java]: I believe only `Tag`s have the `view` command. `Event`s might have one in the future but it is not implemented yet.

File: src/main/java/seedu/address/logic/commands/CommandWord.java [hunk 2]
```diff
@@ -39,16 +41,31 @@
...
         return Optional.ofNullable(inputs.get(inputString)).orElse(DEFAULT);
     }
 
+    public boolean requiresType() {
+        return !validTypes.isEmpty();
+    }
+
+    public String acceptedTypes() {
+        return validTypes.stream().map(CommandType::getTypeString).reduce("", (x, y) -> x + "\n" + y);
+    }
```
Comment (chan-j-d) [inline src/main/java/seedu/address/logic/commands/CommandWord.java]: perhaps this should return a list of accepted `CommandType`s? Otherwise, I think the name is slightly misleading. Maybe something like `getAcceptedTypesString() {..}`

**Review by chan-j-d — CHANGES_REQUESTED** [review]
Some small fixes. Looks good for the most part.

**Comment by zhiayang** [comment]
pog

File: src/main/java/seedu/address/logic/commands/CommandWord.java (hunk 1 above)
Comment (fyshhh) [reply src/main/java/seedu/address/logic/commands/CommandWord.java]: fixed

File: src/main/java/seedu/address/logic/commands/CommandWord.java (hunk 2 above)
Comment (fyshhh) [reply src/main/java/seedu/address/logic/commands/CommandWord.java]: good call.

**Review by chan-j-d — APPROVED** [review]
LGTM!
